var DATA = [
      { id:0, label:"android.nfc", link:"android/nfc/package-summary.html", type:"package" },
      { id:1, label:"android.nfc.FormatException", link:"android/nfc/FormatException.html", type:"class" },
      { id:2, label:"android.nfc.NdefMessage", link:"android/nfc/NdefMessage.html", type:"class" },
      { id:3, label:"android.nfc.NdefRecord", link:"android/nfc/NdefRecord.html", type:"class" },
      { id:4, label:"mobisocial.ndefexchange", link:"mobisocial/ndefexchange/package-summary.html", type:"package" },
      { id:5, label:"mobisocial.ndefexchange.DuplexSocket", link:"mobisocial/ndefexchange/DuplexSocket.html", type:"class" },
      { id:6, label:"mobisocial.ndefexchange.NdefBluetoothPushHandover", link:"mobisocial/ndefexchange/NdefBluetoothPushHandover.html", type:"class" },
      { id:7, label:"mobisocial.ndefexchange.NdefBluetoothPushHandover.BluetoothDuplexSocket", link:"mobisocial/ndefexchange/NdefBluetoothPushHandover.BluetoothDuplexSocket.html", type:"class" },
      { id:8, label:"mobisocial.ndefexchange.NdefExchangeContract", link:"mobisocial/ndefexchange/NdefExchangeContract.html", type:"class" },
      { id:9, label:"mobisocial.ndefexchange.NdefExchangeThread", link:"mobisocial/ndefexchange/NdefExchangeThread.html", type:"class" },
      { id:10, label:"mobisocial.ndefexchange.NdefTcpPushHandover", link:"mobisocial/ndefexchange/NdefTcpPushHandover.html", type:"class" },
      { id:11, label:"mobisocial.ndefexchange.NdefTcpPushHandover.TcpDuplexSocket", link:"mobisocial/ndefexchange/NdefTcpPushHandover.TcpDuplexSocket.html", type:"class" },
      { id:12, label:"mobisocial.ndefexchange.PendingNdefExchange", link:"mobisocial/ndefexchange/PendingNdefExchange.html", type:"class" },
      { id:13, label:"mobisocial.ndefexchange.StreamDuplexSocket", link:"mobisocial/ndefexchange/StreamDuplexSocket.html", type:"class" },
      { id:14, label:"mobisocial.nfc", link:"mobisocial/nfc/package-summary.html", type:"package" },
      { id:15, label:"mobisocial.nfc.ConnectionHandover", link:"mobisocial/nfc/ConnectionHandover.html", type:"class" },
      { id:16, label:"mobisocial.nfc.ConnectionHandoverManager", link:"mobisocial/nfc/ConnectionHandoverManager.html", type:"class" },
      { id:17, label:"mobisocial.nfc.NdefFactory", link:"mobisocial/nfc/NdefFactory.html", type:"class" },
      { id:18, label:"mobisocial.nfc.NdefHandler", link:"mobisocial/nfc/NdefHandler.html", type:"class" },
      { id:19, label:"mobisocial.nfc.Nfc", link:"mobisocial/nfc/Nfc.html", type:"class" },
      { id:20, label:"mobisocial.nfc.Nfc.OnTagWriteListener", link:"mobisocial/nfc/Nfc.OnTagWriteListener.html", type:"class" },
      { id:21, label:"mobisocial.nfc.PrioritizedHandler", link:"mobisocial/nfc/PrioritizedHandler.html", type:"class" },
      { id:22, label:"mobisocial.nfc.addon", link:"mobisocial/nfc/addon/package-summary.html", type:"package" },
      { id:23, label:"mobisocial.nfc.addon.BluetoothConnector", link:"mobisocial/nfc/addon/BluetoothConnector.html", type:"class" },
      { id:24, label:"mobisocial.nfc.addon.BluetoothConnector.OnConnectedListener", link:"mobisocial/nfc/addon/BluetoothConnector.OnConnectedListener.html", type:"class" }

    ];
